
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>AerovelenceMod</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Remove="Common\Systems\Generation\GenUtils\**" />
    <Compile Remove="Common\Systems\Generation\GenUtils\**" />
    <EmbeddedResource Remove="Common\Systems\Generation\GenUtils\**" />
    <None Remove="Common\Systems\Generation\GenUtils\**" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Content\Projectiles\CrystalCaverns\" />
  </ItemGroup>
</Project>