
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>AerovelenceMod</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Remove="Common\Systems\Generation\GenUtils\**" />
    <Compile Remove="Common\Systems\Generation\GenUtils\**" />
    <EmbeddedResource Remove="Common\Systems\Generation\GenUtils\**" />
    <None Remove="Common\Systems\Generation\GenUtils\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Content\Items\Weapons\CrystalCaverns\CrystalCrescent\crystalcrescent.png" />
    <None Remove="Content\Tiles\CrystalCaverns\Rubble\CavernPot2x2Rubble.png" />
    <None Remove="Content\Tiles\CrystalCaverns\Rubble\CavernStone1x1CeilingRubble.png" />
    <None Remove="Content\Tiles\CrystalCaverns\Rubble\CavernStone1x1FloorRubble.png" />
    <None Remove="Content\Tiles\CrystalCaverns\Rubble\CavernStone1x2CeilingRubble.png" />
    <None Remove="Content\Tiles\CrystalCaverns\Rubble\CavernStone1x2FloorRubble.png" />
    <None Remove="Content\Tiles\CrystalCaverns\Rubble\CavernStone3x2FloorRubble.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Content\Projectiles\CrystalCaverns\" />
  </ItemGroup>
</Project>